/**
 * Supervisor backend for hosts with no service manager (#479).
 *
 * A container whose PID 1 is tini has nothing to register autostart with, so
 * `jaw service` previously refused and handed back a manual recipe. That left
 * every operator writing the same loop by hand — the reporter shipped an
 * `ensure-jaw.sh` plus a 60s while-loop to keep `jaw serve` alive.
 *
 * This generates that loop instead. Two properties matter, and are why the
 * generated script is not a naive `while ! pgrep jaw; do start; done`:
 *
 *  1. Liveness is decided by the pidfile's OS start time, the same check
 *     `jaw service stop` uses. A pidfile whose PID has been recycled by an
 *     unrelated process must read as dead, or the supervisor sits forever
 *     beside a server that is not running — the #479 misdiagnosis exactly.
 *  2. Every path is absolute. The supervisor is launched from the same
 *     non-interactive context that cannot resolve `jaw` on PATH.
 */
import { dirname } from 'node:path';

export interface SupervisorContext {
    nodePath: string;
    jawPath: string;
    home: string;
    port: string;
    logPath: string;
    /** Seconds between liveness checks. */
    intervalSeconds: number;
}

function shQuote(value: string): string {
    return "'" + String(value).replace(/'/g, "'\\''") + "'";
}

/**
 * POSIX sh supervisor loop.
 *
 * Deliberately sh, not bash: the hosts that need this are minimal containers
 * where /bin/sh may be dash and bash may not be installed at all.
 */
export function renderSupervisorScript(ctx: SupervisorContext): string {
    const node = shQuote(ctx.nodePath);
    const jaw = shQuote(ctx.jawPath);
    const home = shQuote(ctx.home);
    const log = shQuote(ctx.logPath);
    const interval = Math.max(1, Math.floor(ctx.intervalSeconds));

    return [
        '#!/bin/sh',
        '# Generated by `jaw service --backend supervisor` (#479).',
        '# Keeps one `jaw serve` alive on a host with no service manager.',
        '#',
        '# Every path is absolute on purpose: this runs in a non-interactive shell',
        '# that does not have ' + dirname(ctx.jawPath) + ' on PATH.',
        'set -u',
        '',
        'NODE=' + node,
        'JAW=' + jaw,
        'HOME_DIR=' + home,
        'PORT=' + ctx.port,
        'LOG=' + log,
        'INTERVAL=' + interval,
        '',
        'log() {',
        '    printf \'%s supervisor: %s\\n\' "$(date -u \'+%Y-%m-%dT%H:%M:%SZ\')" "$1" >> "$LOG" 2>&1',
        '}',
        '',
        '# Ask jaw itself whether the instance is alive. `service status` verifies',
        '# the pidfile against the OS process start time, so a recycled PID reads',
        '# as dead instead of masquerading as a healthy server.',
        'is_running() {',
        '    "$NODE" "$JAW" --home "$HOME_DIR" service status --port "$PORT" >/dev/null 2>&1',
        '}',
        '',
        'start_once() {',
        '    log "starting jaw serve on port $PORT"',
        '    # setsid detaches from the controlling terminal so the server outlives',
        '    # the ssh session that started the supervisor. It is util-linux, so it',
        '    # is absent on macOS and on some minimal images; without this guard the',
        '    # loop would fail to start anything at all there. nohup alone still',
        '    # survives SIGHUP, which is the property that matters most.',
        '    if [ -n "$SETSID" ]; then',
        '        "$SETSID" nohup "$NODE" "$JAW" --home "$HOME_DIR" serve --port "$PORT" --no-open \\',
        '            >> "$LOG" 2>&1 < /dev/null &',
        '    else',
        '        nohup "$NODE" "$JAW" --home "$HOME_DIR" serve --port "$PORT" --no-open \\',
        '            >> "$LOG" 2>&1 < /dev/null &',
        '    fi',
        '}',
        '',
        '# Resolved once, not per cycle.',
        'SETSID="$(command -v setsid 2>/dev/null || true)"',
        '',
        'mkdir -p "$(dirname "$LOG")" 2>/dev/null || true',
        '',
        '# Stop supervising when the host stops us, rather than leaving an orphan',
        '# loop that would fight the next start.',
        'trap \'log "supervisor received TERM; exiting"; exit 0\' TERM INT',
        '',
        'while true; do',
        '    if ! is_running; then',
        '        start_once',
        '    fi',
        '    sleep "$INTERVAL"',
        'done',
        '',
    ].join('\n');
}

/** Operator-facing summary after the supervisor script is written. */
export function supervisorInstallSummary(scriptPath: string, ctx: SupervisorContext): string[] {
    return [
        'Supervisor script written: ' + scriptPath,
        '',
        '   This host has no service manager, so nothing starts it at boot for you.',
        '   Wire it into whatever does own startup here:',
        '',
        '     container entrypoint / CMD:  ' + scriptPath,
        '     cron:                        @reboot ' + scriptPath + ' &',
        '     ad-hoc over ssh:             setsid nohup ' + scriptPath + ' >> ' + ctx.logPath + ' 2>&1 < /dev/null &',
        '',
        '   Log:    tail -n 50 ' + ctx.logPath,
        '   Status: ' + ctx.jawPath + ' --home ' + ctx.home + ' service status --port ' + ctx.port,
    ];
}
