// @ts-nocheck -- normalized untrusted JSON is narrowed at runtime below.
import type { ReactElement } from 'react';
export type ChartType = 'bar' | 'line' | 'pie';
export interface ChartJsonSpec { schemaVersion: 'chart-json-v1'; type: ChartType; title: string; description: string; labels: string[]; data: number[] }
const clip = (v: unknown, n: number) => { const s = typeof v === 'string' ? v.trim() : ''; return s.length > n ? `${s.slice(0, n - 1)}…` : s; };
export function normalizeChartJsonSpec(raw: unknown): ChartJsonSpec | null { if (!raw || typeof raw !== 'object') return null; const o = raw as Record<string, unknown>; if (o.schemaVersion !== 'chart-json-v1') return null; const lr = Array.isArray(o.labels) ? o.labels : [], dr = Array.isArray(o.data) ? o.data : []; const labels: string[] = [], data: number[] = []; for (let i = 0; i < Math.min(24, lr.length, dr.length); i++) { const n = Number(dr[i]); if (!Number.isFinite(n)) continue; labels.push(clip(lr[i], 40) || `Item ${i + 1}`); data.push(n); } if (!data.length) return null; return { schemaVersion: 'chart-json-v1', type: o.type === 'line' || o.type === 'pie' ? o.type : 'bar', title: clip(o.title, 120) || 'Chart', description: clip(o.description, 240), labels, data }; }
const colors = ['var(--syntax-blue, var(--accent))', 'var(--syntax-green, var(--accent))', 'var(--syntax-red, var(--accent))', 'var(--syntax-purple, var(--accent))', 'var(--syntax-yellow, var(--accent))', 'var(--syntax-cyan, var(--accent))'];
export function effectiveChartType(spec: ChartJsonSpec): ChartType { return spec.type === 'pie' && spec.data.reduce((s, n) => s + Math.max(0, n), 0) <= 0 ? 'bar' : spec.type; }
export function ChartJsonFence({ spec }: { spec: ChartJsonSpec }): ReactElement { const type = effectiveChartType(spec), max = Math.max(...spec.data.map(Math.abs), 1), total = spec.data.reduce((s, n) => s + Math.max(0, n), 0); let cursor = -Math.PI / 2; const points = spec.data.map((v, i) => `${spec.data.length === 1 ? 180 : i * 360 / (spec.data.length - 1)},${145 - ((v + max) / (2 * max)) * 120}`).join(' '); return <figure className="chart-json-block"><figcaption><strong>{spec.title}</strong>{spec.description && <span>{spec.description}</span>}</figcaption><svg viewBox="0 0 360 170" role="img" aria-labelledby="chart-title chart-desc"><title id="chart-title">{spec.title}</title><desc id="chart-desc">{spec.description || `${type} chart with ${spec.data.length} points`}</desc>{type === 'bar' && spec.data.map((v, i) => <rect key={i} x={i * (350 / spec.data.length)} y={145 - Math.max(0, v / max) * 120} width={Math.max(5, 340 / spec.data.length)} height={Math.max(1, Math.max(0, v / max) * 120)} fill={colors[i % colors.length]}><title>{spec.labels[i]}: {v}</title></rect>)}{type === 'line' && <><polyline points={points} fill="none" stroke="var(--accent)" strokeWidth="2.5" />{spec.data.map((v, i) => { const [x, y] = points.split(' ')[i]!.split(','); return <circle key={i} cx={x} cy={y} r="3" fill={colors[i % colors.length]}><title>{spec.labels[i]}: {v}</title></circle>; })}</>}{type === 'pie' && spec.data.map((v, i) => { const size = Math.max(0, v) / total * Math.PI * 2, start = cursor, end = cursor += size, sx = 180 + 64 * Math.cos(start), sy = 85 + 64 * Math.sin(start), ex = 180 + 64 * Math.cos(end), ey = 85 + 64 * Math.sin(end); return <path key={i} d={`M 180 85 L ${sx} ${sy} A 64 64 0 ${size > Math.PI ? 1 : 0} 1 ${ex} ${ey} Z`} fill={colors[i % colors.length]}><title>{spec.labels[i]}: {v}</title></path>; })}</svg><div className="chart-json-legend">{spec.labels.map((l, i) => <span key={i}>{l}: {spec.data[i]}</span>)}</div></figure>; }
