// @ts-nocheck -- normalized untrusted JSON is narrowed at runtime below.
import { useState, type ReactElement } from 'react';
import { useRenderActionPorts } from '../../../providers/render-action-ports.tsx';
import { copyWithFeedback } from './copy-feedback.ts';
export type ComposeKind = 'email' | 'message' | 'document' | 'other'; export interface ComposeVariant { id: string; label: string; subject: string; body: string } export interface ComposeBlockSpec { schemaVersion: 'compose-block-v1'; kind: ComposeKind; title: string; subject: string; variants: ComposeVariant[] }
const txt = (v: unknown, n: number) => { const s = typeof v === 'string' ? v.trim() : ''; return s.slice(0, n); }; const list = (v: unknown, n: number, join: string) => { if (!Array.isArray(v)) return ''; let used = 0; return v.map(x => txt(x, n - used)).filter(x => { used += x.length; return Boolean(x); }).join(join).slice(0, n); };
function body(o: Record<string, unknown>) { return txt(o.body, 20_000) || list(o.paragraphs, 20_000, '\n\n') || list(o.bodyLines, 20_000, '\n'); }
export function normalizeComposeBlockSpec(raw: unknown): ComposeBlockSpec | null { if (!raw || typeof raw !== 'object') return null; const o = raw as Record<string, unknown>; if (o.schemaVersion !== 'compose-block-v1') return null; const subject = txt(o.subject, 180), kind: ComposeKind = o.kind === 'email' || o.kind === 'message' || o.kind === 'document' || o.kind === 'other' ? o.kind : o.kind === 'textMessage' ? 'message' : 'other'; const variants = (Array.isArray(o.variants) ? o.variants : []).map((v, i) => { if (!v || typeof v !== 'object') return null; const x = v as Record<string, unknown>, b = body(x); return b ? { id: txt(x.id, 60) || `variant_${i + 1}`, label: txt(x.label, 40) || `Variant ${i + 1}`, subject: txt(x.subject, 180) || subject, body: b } : null; }).filter((v): v is ComposeVariant => Boolean(v)).slice(0, 3); return variants.length ? { schemaVersion: 'compose-block-v1', kind, title: txt(o.title, 120) || 'Draft', subject, variants } : null; }
export function composeFollowupPrompt(spec: ComposeBlockSpec, subject: string, draft: string, instruction: string): string { const label = spec.kind === 'document' ? 'Title' : spec.kind === 'message' ? 'Topic' : 'Subject'; return ['다음 compose-block 초안을 사용자가 편집했습니다.','',`종류: ${spec.kind}`,`카드 제목: ${spec.title}`,'',`${label}:`,subject || '(비어 있음)','','본문:',draft || '(비어 있음)','','사용자 추가 요청:',instruction,'','위 수정본과 추가 요청을 반영해서 새 compose-block 초안을 다시 작성해주세요. 결과는 strict JSON compose-block으로 반환하고, 멀티라인 본문은 variants[].paragraphs 또는 variants[].bodyLines 배열을 우선 사용해주세요.'].join('\n'); }
export function ComposeBlockFence({ spec }: { spec: ComposeBlockSpec }): ReactElement { const ports = useRenderActionPorts(); const [active, setActive] = useState(0), [subject, setSubject] = useState(spec.variants[0]!.subject), [draft, setDraft] = useState(spec.variants[0]!.body), [followup, setFollowup] = useState(''), [notice, setNotice] = useState(''); const choose = (i: number) => { setActive(i); setSubject(spec.variants[i]!.subject); setDraft(spec.variants[i]!.body); }; const send = async () => { const instruction = followup.trim().slice(0, 4000); if (!instruction) { setNotice('추가 요청을 입력한 뒤 Send를 눌러주세요.'); return; } try { await ports.submitMessage(composeFollowupPrompt(spec, subject, draft, instruction)); setFollowup(''); setNotice('전송했습니다.'); } catch (e) { setNotice(e instanceof Error ? e.message : '전송하지 못했습니다.'); } }; return <section className="compose-block"><header>{spec.title}</header><div role="group" aria-label="Draft variants">{spec.variants.map((v, i) => <button key={v.id} aria-pressed={i === active} onClick={() => choose(i)}>{v.label}</button>)}</div><label>Subject<input maxLength={180} value={subject} onChange={e => setSubject(e.target.value)} /></label><textarea maxLength={20_000} value={draft} onChange={e => setDraft(e.target.value)} /><button onClick={() => void copyWithFeedback((t) => ports.copyText(t), subject ? `${subject}\n\n${draft}` : draft).then((outcome) => { if (outcome.ok) { ports.announce('Draft copied'); } else { setNotice(`Copy failed: ${outcome.message}`); } })}>Copy</button>{spec.kind === 'email' && <button onClick={() => ports.openProtocol(`mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(draft)}`)}>Open in Mail</button>}{spec.kind === 'message' && <button onClick={() => ports.openProtocol(`sms:?body=${encodeURIComponent(draft)}`)}>Open in Messages</button>}<textarea aria-label="Prompt" maxLength={4000} value={followup} onChange={e => setFollowup(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && (e.metaKey || e.ctrlKey) && !e.shiftKey) { e.preventDefault(); void send(); } }} /><div role="alert">{notice}</div><button onClick={() => void send()}>Send</button></section>; }
